---
- name: Test Actions
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
      register: ret

    - name: Show results
      ansible.builtin.assert:
        that:
          - ret['ansible_facts']['ansible_fqdnn'] is defined
