---
- hosts: all
  gather_facts: false

  tasks:
#    - name: gather facts
#      ansible.builtin.setup:
#      register: ret
#
#    - name: show results
#      ansible.builtin.debug:
#        var: ret

    - name: install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: open http/https port
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled

    - name: start httpd service
      ansible.builtin.systemd:
        state: started
        name: httpd
