---
- name: Test Actions
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather facts 3
      ansible.builtin.setup:
      register: ret

    - name: Show results
      ansible.builtin.debug:
        var: ret['ansible_facts']['ansible_fqdn']
