name: Ansible Playbook
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: hostname

      - name: install ansible 
        run: pip install ansible-lint

      - name: style check 
        run: ansible-lint site.yml
