name: Ansible Playbook
on: push

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run playbook
        # run: ansible-navigator run site.yml -m stdout
        run: hostname