name: Ansible Playbook
on: push

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure that the playbook pass ansible-lint rules
        run: ansible-navigator lint site.yml
        # run: |
        #   source ~/.venv/python3.9-ansible/bin/activate
        #   ansible-lint site.yml --offline
        # run: ansible-navigator run site.yml -m stdout

  test:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure that the playbook run successful.
        run: ansible-navigator run site.yml -i inventory