name: Ansible Playbook
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run the command
        run: hostname

      - name: install ansible-lint
        run: pip install ansible-lint

      - name: style check 
        run: ansible-lint site.yml
