name: Ansible Playbook
on: push

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: style check 
        run: ansible-lint site.yml
