name: Ansible Playbook CI
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main]

jobs:
  lint:
    runs-on: self-hosted
    container: registry.redhat.io/ansible-automation-platform-25/ansible-dev-tools-rhel8:25.2.0-18
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure that the playbook pass ansible-lint rules
        run: ansible-lint site.yml
        # run: ansible-navigator lint site.yml
        # run: |
        #   source ~/.venv/python3.9-ansible/bin/activate
        #   ansible-lint site.yml --offline
        # run: ansible-navigator run site.yml -m stdout

  test:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure that the playbook run successful.
        run: ansible-playbook site.yml -i inventory
